API_KEY='111'
API_SECRET='222'
TOKEN='333'

MONGO_USER='44'
MONGO_SECRET='555'
MONGO_URL='mongodb://xxx'

DB_NAME='prod'
BOARD_NAME='Ogloszenia'
COLLECTION_NAME='offers'

FORBIDDEN_WORDS = ['sokolka', 'sokółka', 'sokólka']

MAX_PRICE = 400000

DAYS_TO_CHECK = 7